name: realturn_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  firebase_core: ^3.13.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.1
  video_player: ^2.8.3
  cached_network_image: ^3.3.1
  file_picker: ^10.1.2
  http: ^1.2.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  app_links: ^3.1.0
  firebase_auth: 5.5.4
  dots_indicator: ^4.0.1
  intl_phone_number_input: ^0.7.3+1
  webview_flutter: 4.0.7
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    
    # Remove assets/image/ if not needed, or ensure it exists
    # - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900